package:
  name: asrad-reader
  version: 0.4.5

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11.7
    - numpy >=1.26.2
    - pandas >=2.1.4

about:
  summary: A toolkit for processing CWA long-term observation station data.
  home: https://github.com/wyork507/python_asrad_reader
  license: MIT
  license_file: LICENSE
